[package]
name = "phonon_client_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcsc = "2"
secp256k1 = { version = "0", features = ["rand-std"] }
rand = "0"
